const ADD_TODO = 'ADD_TODO';
const DELETE_TODO = 'REMOVE_TODO';
const TOGGLE_TODO = 'TOGGLE_TODO';
const SEARCH_KEYWORD = 'SEARCH_KEYWORD';
const EDIT_TODO = 'EDIT_TODO';

export {
  ADD_TODO,
  TOGGLE_TODO,
  DELETE_TODO,
  SEARCH_KEYWORD,
  EDIT_TODO
};